services:
  app:
    image: aliansari8179/flaskapp_1:1.0
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy  # Wait until db is healthy
    env_file: .env

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5